
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

import java.util.*;
import java_cup.runtime.Symbol;
import Views.*;
import Entorno.Simbolo.EnumTipoDato;
import Expresion.Operacion.Tipo_operacion;
import Expresion.*;
import Instruccion.*;
import Entorno.Simbolo;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class SintacticoArit extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return Syma.class;
}

  /** Default constructor. */
  @Deprecated
  public SintacticoArit() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public SintacticoArit(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public SintacticoArit(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\016\000\002\002\004\000\002\004\003\000\002\005" +
    "\004\000\002\005\003\000\002\003\003\000\002\006\005" +
    "\000\002\002\004\000\002\002\005\000\002\002\005\000" +
    "\002\002\005\000\002\002\005\000\002\002\005\000\002" +
    "\002\003\000\002\002\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\030\000\004\004\010\001\002\000\006\002\ufffd\004" +
    "\ufffd\001\002\000\006\002\ufffe\004\ufffe\001\002\000\004" +
    "\002\032\001\002\000\006\002\000\004\010\001\002\000" +
    "\004\022\011\001\002\000\010\004\015\016\014\031\012" +
    "\001\002\000\010\004\015\016\014\031\012\001\002\000" +
    "\020\002\ufffc\004\ufffc\030\016\031\017\032\021\033\022" +
    "\034\020\001\002\000\020\002\ufff4\004\ufff4\030\ufff4\031" +
    "\ufff4\032\ufff4\033\ufff4\034\ufff4\001\002\000\020\002\ufff5" +
    "\004\ufff5\030\ufff5\031\ufff5\032\ufff5\033\ufff5\034\ufff5\001" +
    "\002\000\010\004\015\016\014\031\012\001\002\000\010" +
    "\004\015\016\014\031\012\001\002\000\010\004\015\016" +
    "\014\031\012\001\002\000\010\004\015\016\014\031\012" +
    "\001\002\000\010\004\015\016\014\031\012\001\002\000" +
    "\020\002\ufff7\004\ufff7\030\ufff7\031\ufff7\032\ufff7\033\ufff7" +
    "\034\020\001\002\000\020\002\ufff8\004\ufff8\030\ufff8\031" +
    "\ufff8\032\ufff8\033\ufff8\034\020\001\002\000\020\002\ufff6" +
    "\004\ufff6\030\ufff6\031\ufff6\032\ufff6\033\ufff6\034\ufff6\001" +
    "\002\000\020\002\ufff9\004\ufff9\030\ufff9\031\ufff9\032\021" +
    "\033\022\034\020\001\002\000\020\002\ufffa\004\ufffa\030" +
    "\ufffa\031\ufffa\032\021\033\022\034\020\001\002\000\020" +
    "\002\ufffb\004\ufffb\030\ufffb\031\ufffb\032\021\033\022\034" +
    "\020\001\002\000\006\002\uffff\004\uffff\001\002\000\004" +
    "\002\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\030\000\012\003\004\004\005\005\006\006\003\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\006\003\030\006\003\001\001\000\002\001\001\000" +
    "\004\002\012\001\001\000\004\002\027\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\002" +
    "\026\001\001\000\004\002\025\001\001\000\004\002\024" +
    "\001\001\000\004\002\023\001\001\000\004\002\022\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$SintacticoArit$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$SintacticoArit$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$SintacticoArit$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


  
    /*public static LinkedList<AcepErr> TablaErr=new LinkedList<AcepErr>();*/

    //public Panel resultado;
    public LinkedList<Instruccion> resultado = new LinkedList<>();
    

    //Metodo al que se llama automaticamente ante algun error sintactico
    public void syntax_error(Symbol s)
    {        
        String lexema = s.value.toString();
        int fila = s.right;
        int columna = s.left;
        
        System.out.println("!!!!!!! Error Sintactico Recuperado !!!!!!!");
        System.out.println("\t\tLexema: "+lexema);
        System.out.println("\t\tFila: "+fila);
        System.out.println("\t\tColumna: "+columna);

        //lista_errores.add(new ErrorT(lexema, fila, columna,"sintactico" ,"Simbolo no esperado"));
        /*AcepErr datos =new AcepErr(lexema, "ERROR SINTACTICO" ,fila,columna,"Simbolo no esperado");
            TablaErr.add(datos);
            */
    }

    //Metodo al que se llama en el momento en que ya no es posible una recuperacion de errores
    public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception
    {        
        String lexema = s.value.toString();
        int fila = s.right;
        int columna = s.left;
        
        System.out.println("!!!!!!! Error Sintactico, Panic Mode !!!!!!! ");
        System.out.println("\t\tLexema: "+lexema);
        System.out.println("\t\tFila: "+fila);
        System.out.println("\t\tColumna: "+columna);

       /*AcepErr datos =new AcepErr(lexema, "ERROR SINTACTICO" ,fila,columna,"Simbolo no esperado Error Fatal");
                   TablaErr.add(datos);
                  */
        //lista_errores.add(new ErrorT(lexema, fila, columna,"sintactico" ,"Simbolo no esperado, Panic Mode"));
    }

    public void semantic(Symbol cur_token, String n) 
    {
        System.out.println("error semantico ");
    }

    public void semantic(String msg, Object obj) {}



/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$SintacticoArit$actions {




  private final SintacticoArit parser;

  /** Constructor */
  CUP$SintacticoArit$actions(SintacticoArit parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$SintacticoArit$do_action_part00000000(
    int                        CUP$SintacticoArit$act_num,
    java_cup.runtime.lr_parser CUP$SintacticoArit$parser,
    java.util.Stack            CUP$SintacticoArit$stack,
    int                        CUP$SintacticoArit$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$SintacticoArit$result;

      /* select the action based on the action number */
      switch (CUP$SintacticoArit$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= LISTA EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$SintacticoArit$stack.elementAt(CUP$SintacticoArit$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$SintacticoArit$stack.elementAt(CUP$SintacticoArit$top-1)).right;
		LinkedList<Instruccion> start_val = (LinkedList<Instruccion>)((java_cup.runtime.Symbol) CUP$SintacticoArit$stack.elementAt(CUP$SintacticoArit$top-1)).value;
		RESULT = start_val;
              CUP$SintacticoArit$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$SintacticoArit$stack.elementAt(CUP$SintacticoArit$top-1)), ((java_cup.runtime.Symbol)CUP$SintacticoArit$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$SintacticoArit$parser.done_parsing();
          return CUP$SintacticoArit$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // LISTA ::= LISTAINSTRUCCIONES 
            {
              LinkedList<Instruccion> RESULT =null;
		int lileft = ((java_cup.runtime.Symbol)CUP$SintacticoArit$stack.peek()).left;
		int liright = ((java_cup.runtime.Symbol)CUP$SintacticoArit$stack.peek()).right;
		LinkedList<Instruccion> li = (LinkedList<Instruccion>)((java_cup.runtime.Symbol) CUP$SintacticoArit$stack.peek()).value;
		
            parser.resultado=li;
        
              CUP$SintacticoArit$result = parser.getSymbolFactory().newSymbol("LISTA",2, ((java_cup.runtime.Symbol)CUP$SintacticoArit$stack.peek()), ((java_cup.runtime.Symbol)CUP$SintacticoArit$stack.peek()), RESULT);
            }
          return CUP$SintacticoArit$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // LISTAINSTRUCCIONES ::= LISTAINSTRUCCIONES INSTRUCCION 
            {
              LinkedList<Instruccion> RESULT =null;
		int lileft = ((java_cup.runtime.Symbol)CUP$SintacticoArit$stack.elementAt(CUP$SintacticoArit$top-1)).left;
		int liright = ((java_cup.runtime.Symbol)CUP$SintacticoArit$stack.elementAt(CUP$SintacticoArit$top-1)).right;
		LinkedList<Instruccion> li = (LinkedList<Instruccion>)((java_cup.runtime.Symbol) CUP$SintacticoArit$stack.elementAt(CUP$SintacticoArit$top-1)).value;
		int insleft = ((java_cup.runtime.Symbol)CUP$SintacticoArit$stack.peek()).left;
		int insright = ((java_cup.runtime.Symbol)CUP$SintacticoArit$stack.peek()).right;
		Instruccion ins = (Instruccion)((java_cup.runtime.Symbol) CUP$SintacticoArit$stack.peek()).value;
		
                        RESULT=li;
                        RESULT.add(ins);
                    
              CUP$SintacticoArit$result = parser.getSymbolFactory().newSymbol("LISTAINSTRUCCIONES",3, ((java_cup.runtime.Symbol)CUP$SintacticoArit$stack.elementAt(CUP$SintacticoArit$top-1)), ((java_cup.runtime.Symbol)CUP$SintacticoArit$stack.peek()), RESULT);
            }
          return CUP$SintacticoArit$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // LISTAINSTRUCCIONES ::= INSTRUCCION 
            {
              LinkedList<Instruccion> RESULT =null;
		int insleft = ((java_cup.runtime.Symbol)CUP$SintacticoArit$stack.peek()).left;
		int insright = ((java_cup.runtime.Symbol)CUP$SintacticoArit$stack.peek()).right;
		Instruccion ins = (Instruccion)((java_cup.runtime.Symbol) CUP$SintacticoArit$stack.peek()).value;
		
                        RESULT = new LinkedList<>();
                        RESULT.add(ins);
                    
              CUP$SintacticoArit$result = parser.getSymbolFactory().newSymbol("LISTAINSTRUCCIONES",3, ((java_cup.runtime.Symbol)CUP$SintacticoArit$stack.peek()), ((java_cup.runtime.Symbol)CUP$SintacticoArit$stack.peek()), RESULT);
            }
          return CUP$SintacticoArit$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // INSTRUCCION ::= DECLARACION 
            {
              Instruccion RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$SintacticoArit$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$SintacticoArit$stack.peek()).right;
		Instruccion a = (Instruccion)((java_cup.runtime.Symbol) CUP$SintacticoArit$stack.peek()).value;
		RESULT=a;
              CUP$SintacticoArit$result = parser.getSymbolFactory().newSymbol("INSTRUCCION",1, ((java_cup.runtime.Symbol)CUP$SintacticoArit$stack.peek()), ((java_cup.runtime.Symbol)CUP$SintacticoArit$stack.peek()), RESULT);
            }
          return CUP$SintacticoArit$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // DECLARACION ::= tId tIgual E 
            {
              Instruccion RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$SintacticoArit$stack.elementAt(CUP$SintacticoArit$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$SintacticoArit$stack.elementAt(CUP$SintacticoArit$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$SintacticoArit$stack.elementAt(CUP$SintacticoArit$top-2)).value;
		int expleft = ((java_cup.runtime.Symbol)CUP$SintacticoArit$stack.peek()).left;
		int expright = ((java_cup.runtime.Symbol)CUP$SintacticoArit$stack.peek()).right;
		Expresion exp = (Expresion)((java_cup.runtime.Symbol) CUP$SintacticoArit$stack.peek()).value;
		RESULT= new Declaracion(id,exp);
              CUP$SintacticoArit$result = parser.getSymbolFactory().newSymbol("DECLARACION",4, ((java_cup.runtime.Symbol)CUP$SintacticoArit$stack.elementAt(CUP$SintacticoArit$top-2)), ((java_cup.runtime.Symbol)CUP$SintacticoArit$stack.peek()), RESULT);
            }
          return CUP$SintacticoArit$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // E ::= tResta E 
            {
              Expresion RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$SintacticoArit$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$SintacticoArit$stack.peek()).right;
		Expresion a = (Expresion)((java_cup.runtime.Symbol) CUP$SintacticoArit$stack.peek()).value;
		RESULT=new Operacion(a,Operacion.Tipo_operacion.NEGATIVO);
              CUP$SintacticoArit$result = parser.getSymbolFactory().newSymbol("E",0, ((java_cup.runtime.Symbol)CUP$SintacticoArit$stack.elementAt(CUP$SintacticoArit$top-1)), ((java_cup.runtime.Symbol)CUP$SintacticoArit$stack.peek()), RESULT);
            }
          return CUP$SintacticoArit$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // E ::= E tSuma E 
            {
              Expresion RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$SintacticoArit$stack.elementAt(CUP$SintacticoArit$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$SintacticoArit$stack.elementAt(CUP$SintacticoArit$top-2)).right;
		Expresion a = (Expresion)((java_cup.runtime.Symbol) CUP$SintacticoArit$stack.elementAt(CUP$SintacticoArit$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$SintacticoArit$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$SintacticoArit$stack.peek()).right;
		Expresion b = (Expresion)((java_cup.runtime.Symbol) CUP$SintacticoArit$stack.peek()).value;
		RESULT=new Operacion(a,b,Operacion.Tipo_operacion.SUMA);
              CUP$SintacticoArit$result = parser.getSymbolFactory().newSymbol("E",0, ((java_cup.runtime.Symbol)CUP$SintacticoArit$stack.elementAt(CUP$SintacticoArit$top-2)), ((java_cup.runtime.Symbol)CUP$SintacticoArit$stack.peek()), RESULT);
            }
          return CUP$SintacticoArit$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // E ::= E tResta E 
            {
              Expresion RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$SintacticoArit$stack.elementAt(CUP$SintacticoArit$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$SintacticoArit$stack.elementAt(CUP$SintacticoArit$top-2)).right;
		Expresion a = (Expresion)((java_cup.runtime.Symbol) CUP$SintacticoArit$stack.elementAt(CUP$SintacticoArit$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$SintacticoArit$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$SintacticoArit$stack.peek()).right;
		Expresion b = (Expresion)((java_cup.runtime.Symbol) CUP$SintacticoArit$stack.peek()).value;
		RESULT=new Operacion(a,b,Operacion.Tipo_operacion.RESTA);
              CUP$SintacticoArit$result = parser.getSymbolFactory().newSymbol("E",0, ((java_cup.runtime.Symbol)CUP$SintacticoArit$stack.elementAt(CUP$SintacticoArit$top-2)), ((java_cup.runtime.Symbol)CUP$SintacticoArit$stack.peek()), RESULT);
            }
          return CUP$SintacticoArit$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // E ::= E tMult E 
            {
              Expresion RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$SintacticoArit$stack.elementAt(CUP$SintacticoArit$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$SintacticoArit$stack.elementAt(CUP$SintacticoArit$top-2)).right;
		Expresion a = (Expresion)((java_cup.runtime.Symbol) CUP$SintacticoArit$stack.elementAt(CUP$SintacticoArit$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$SintacticoArit$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$SintacticoArit$stack.peek()).right;
		Expresion b = (Expresion)((java_cup.runtime.Symbol) CUP$SintacticoArit$stack.peek()).value;
		RESULT=new Operacion(a,b,Operacion.Tipo_operacion.MULTIPLICACION);
              CUP$SintacticoArit$result = parser.getSymbolFactory().newSymbol("E",0, ((java_cup.runtime.Symbol)CUP$SintacticoArit$stack.elementAt(CUP$SintacticoArit$top-2)), ((java_cup.runtime.Symbol)CUP$SintacticoArit$stack.peek()), RESULT);
            }
          return CUP$SintacticoArit$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // E ::= E tDiv E 
            {
              Expresion RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$SintacticoArit$stack.elementAt(CUP$SintacticoArit$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$SintacticoArit$stack.elementAt(CUP$SintacticoArit$top-2)).right;
		Expresion a = (Expresion)((java_cup.runtime.Symbol) CUP$SintacticoArit$stack.elementAt(CUP$SintacticoArit$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$SintacticoArit$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$SintacticoArit$stack.peek()).right;
		Expresion b = (Expresion)((java_cup.runtime.Symbol) CUP$SintacticoArit$stack.peek()).value;
		RESULT=new Operacion(a,b,Operacion.Tipo_operacion.DIVISION);
              CUP$SintacticoArit$result = parser.getSymbolFactory().newSymbol("E",0, ((java_cup.runtime.Symbol)CUP$SintacticoArit$stack.elementAt(CUP$SintacticoArit$top-2)), ((java_cup.runtime.Symbol)CUP$SintacticoArit$stack.peek()), RESULT);
            }
          return CUP$SintacticoArit$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // E ::= E tPow E 
            {
              Expresion RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$SintacticoArit$stack.elementAt(CUP$SintacticoArit$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$SintacticoArit$stack.elementAt(CUP$SintacticoArit$top-2)).right;
		Expresion a = (Expresion)((java_cup.runtime.Symbol) CUP$SintacticoArit$stack.elementAt(CUP$SintacticoArit$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$SintacticoArit$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$SintacticoArit$stack.peek()).right;
		Expresion b = (Expresion)((java_cup.runtime.Symbol) CUP$SintacticoArit$stack.peek()).value;
		RESULT=new Operacion(a,b,Operacion.Tipo_operacion.POTENCIA);
              CUP$SintacticoArit$result = parser.getSymbolFactory().newSymbol("E",0, ((java_cup.runtime.Symbol)CUP$SintacticoArit$stack.elementAt(CUP$SintacticoArit$top-2)), ((java_cup.runtime.Symbol)CUP$SintacticoArit$stack.peek()), RESULT);
            }
          return CUP$SintacticoArit$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // E ::= tId 
            {
              Expresion RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$SintacticoArit$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$SintacticoArit$stack.peek()).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$SintacticoArit$stack.peek()).value;
		RESULT=new Operacion(a,Tipo_operacion.IDENTIFICADOR);
              CUP$SintacticoArit$result = parser.getSymbolFactory().newSymbol("E",0, ((java_cup.runtime.Symbol)CUP$SintacticoArit$stack.peek()), ((java_cup.runtime.Symbol)CUP$SintacticoArit$stack.peek()), RESULT);
            }
          return CUP$SintacticoArit$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // E ::= tEntero 
            {
              Expresion RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$SintacticoArit$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$SintacticoArit$stack.peek()).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$SintacticoArit$stack.peek()).value;
		RESULT=new Operacion(a,Tipo_operacion.NUMERO);
              CUP$SintacticoArit$result = parser.getSymbolFactory().newSymbol("E",0, ((java_cup.runtime.Symbol)CUP$SintacticoArit$stack.peek()), ((java_cup.runtime.Symbol)CUP$SintacticoArit$stack.peek()), RESULT);
            }
          return CUP$SintacticoArit$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$SintacticoArit$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$SintacticoArit$do_action(
    int                        CUP$SintacticoArit$act_num,
    java_cup.runtime.lr_parser CUP$SintacticoArit$parser,
    java.util.Stack            CUP$SintacticoArit$stack,
    int                        CUP$SintacticoArit$top)
    throws java.lang.Exception
    {
              return CUP$SintacticoArit$do_action_part00000000(
                               CUP$SintacticoArit$act_num,
                               CUP$SintacticoArit$parser,
                               CUP$SintacticoArit$stack,
                               CUP$SintacticoArit$top);
    }
}

}
